// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy.Core.Data;

#nullable disable

namespace Pharmacy.Core.Data.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20261006032453_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Pharmacy.Core.Data.DailySequence", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("DailySequence");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.BatchAllocation", b =>
                {
                    b.Property<string>("AllocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaleItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AllocationId");

                    b.HasIndex("BatchId");

                    b.HasIndex("SaleItemId");

                    b.ToTable("BatchAllocations", t =>
                        {
                            t.HasCheckConstraint("CK_BatchAllocation_AllocationQuantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.CartItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "DrugId");

                    b.HasIndex("DrugId");

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_CartQuantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Drug", b =>
                {
                    b.Property<string>("DrugId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaleUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs", t =>
                        {
                            t.HasCheckConstraint("CK_Drug_DrugRules", "length(trim(Name)) > 0 AND length(trim(SaleUnit)) > 0 AND CAST(UnitPrice AS REAL) > 0 AND CAST(UnitPrice AS REAL) = CAST(UnitPrice AS INTEGER) AND LowStockThreshold >= 0 AND (IsControlled = 0 OR RequiresPrescription = 1)");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.DrugBatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("BatchId");

                    b.HasIndex("DrugId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("DrugBatches", t =>
                        {
                            t.HasCheckConstraint("CK_DrugBatch_BatchQuantity", "InitialQuantity > 0 AND Quantity >= 0 AND Quantity <= InitialQuantity AND length(trim(BatchNumber)) > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandledByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiveMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.HasIndex("HandledByUserId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_OrderRules", "SaleKind IN ('OTC','Prescription') AND ReceiveMethod IN ('Pickup','Delivery') AND Status IN ('WaitingReview','AwaitingPayment','Preparing','Delivering','Completed','Cancelled','Rejected') AND length(trim(ReceiverName)) > 0 AND length(trim(Phone)) > 0 AND (ReceiveMethod <> 'Delivery' OR (Address IS NOT NULL AND length(trim(Address)) > 0)) AND (SaleKind <> 'Prescription' OR (PrescriptionId IS NOT NULL AND PatientId IS NOT NULL)) AND CAST(TotalAmount AS REAL) >= 0 AND CAST(TotalAmount AS REAL) = CAST(TotalAmount AS INTEGER)");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderItemId");

                    b.HasIndex("DrugId");

                    b.HasIndex("OrderId", "DrugId")
                        .IsUnique();

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Money", "Quantity > 0 AND CAST(UnitPrice AS REAL) > 0 AND CAST(UnitPrice AS REAL) = CAST(UnitPrice AS INTEGER) AND CAST(LineTotal AS REAL) = Quantity * CAST(UnitPrice AS REAL)");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReceivedAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BankReference")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Confirmed'");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_PaymentRules", "CAST(ExpectedAmount AS REAL) > 0 AND CAST(ExpectedAmount AS REAL) = CAST(ExpectedAmount AS INTEGER) AND (ReceivedAmount IS NULL OR (CAST(ReceivedAmount AS REAL) >= 0 AND CAST(ReceivedAmount AS REAL) = CAST(ReceivedAmount AS INTEGER))) AND (Status <> 'Confirmed' OR (BankReference IS NOT NULL AND ApprovedByUserId IS NOT NULL AND ApprovedAt IS NOT NULL AND CAST(ReceivedAmount AS REAL) >= CAST(ExpectedAmount AS REAL)))");

                            t.HasCheckConstraint("CK_Payment_PaymentStatus", "Status IN ('PendingReview','Confirmed','Closed') AND length(trim(BankName)) > 0 AND length(trim(AccountNumber)) > 0 AND length(trim(AccountName)) > 0 AND length(trim(QrImagePath)) > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PaymentSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrImagePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentSettings", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSetting_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Prescription", b =>
                {
                    b.Property<string>("PrescriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriberName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("Prescriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Prescription_PrescriptionRules", "Status IN ('PendingReview','Approved','Rejected','Cancelled') AND length(trim(PatientId)) > 0 AND length(trim(PatientName)) > 0 AND (IssueDate IS NULL OR ValidUntil IS NULL OR IssueDate <= ValidUntil) AND (Status <> 'Approved' OR (IssueDate IS NOT NULL AND ValidUntil IS NOT NULL AND PrescriberName IS NOT NULL AND length(trim(PrescriberName)) > 0))");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PrescriptionItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DispensedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescribedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrescriptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PrescriptionId", "DrugId")
                        .IsUnique();

                    b.ToTable("PrescriptionItems", t =>
                        {
                            t.HasCheckConstraint("CK_PrescriptionItem_PrescriptionQuantity", "PrescribedQuantity > 0 AND DispensedQuantity >= 0 AND DispensedQuantity <= PrescribedQuantity");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Sale", b =>
                {
                    b.Property<string>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("SaleId");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Completed' AND \"OrderId\" IS NOT NULL");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Sales", t =>
                        {
                            t.HasCheckConstraint("CK_Sale_SaleRules", "Kind IN ('OTC','Prescription') AND Channel IN ('Counter','Online') AND Status IN ('Draft','Completed','Cancelled') AND CAST(TotalAmount AS REAL) >= 0 AND CAST(TotalAmount AS REAL) = CAST(TotalAmount AS INTEGER) AND (Kind <> 'Prescription' OR (PrescriptionId IS NOT NULL AND PatientId IS NOT NULL)) AND (Status <> 'Completed' OR (CompletedAt IS NOT NULL AND PaymentMethod IS NOT NULL AND ((Channel='Counter' AND PaymentMethod='Cash') OR (Channel='Online' AND PaymentMethod='ManualQR'))))");
                        });

                    b.HasDiscriminator<string>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.SaleItem", b =>
                {
                    b.Property<string>("SaleItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("SaleItemId");

                    b.HasIndex("DrugId");

                    b.HasIndex("SaleId", "DrugId")
                        .IsUnique();

                    b.ToTable("SaleItems", t =>
                        {
                            t.HasCheckConstraint("CK_SaleItem_Money", "Quantity > 0 AND CAST(UnitPrice AS REAL) > 0 AND CAST(UnitPrice AS REAL) = CAST(UnitPrice AS INTEGER) AND CAST(LineTotal AS REAL) = Quantity * CAST(UnitPrice AS REAL)");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.StockReservation", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriptionItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReservationId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PrescriptionItemId");

                    b.HasIndex("OrderId", "DrugId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("StockReservations", t =>
                        {
                            t.HasCheckConstraint("CK_StockReservation_ReservationRules", "Quantity > 0 AND Status IN ('Active','Consumed','Released')");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.UserAccount", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("UserAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccount_AccountRules", "length(Username) BETWEEN 3 AND 30 AND Username NOT GLOB '*[^A-Za-z0-9._-]*' AND length(PasswordHash) > 0 AND NormalizedUsername = upper(trim(Username)) AND Role IN ('User','Staff','Admin')");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.OTCSale", b =>
                {
                    b.HasBaseType("Pharmacy.Core.Domain.Sale");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Sale_SaleRules", "Kind IN ('OTC','Prescription') AND Channel IN ('Counter','Online') AND Status IN ('Draft','Completed','Cancelled') AND CAST(TotalAmount AS REAL) >= 0 AND CAST(TotalAmount AS REAL) = CAST(TotalAmount AS INTEGER) AND (Kind <> 'Prescription' OR (PrescriptionId IS NOT NULL AND PatientId IS NOT NULL)) AND (Status <> 'Completed' OR (CompletedAt IS NOT NULL AND PaymentMethod IS NOT NULL AND ((Channel='Counter' AND PaymentMethod='Cash') OR (Channel='Online' AND PaymentMethod='ManualQR'))))");
                        });

                    b.HasDiscriminator().HasValue("OTC");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PrescriptionSale", b =>
                {
                    b.HasBaseType("Pharmacy.Core.Domain.Sale");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Sale_SaleRules", "Kind IN ('OTC','Prescription') AND Channel IN ('Counter','Online') AND Status IN ('Draft','Completed','Cancelled') AND CAST(TotalAmount AS REAL) >= 0 AND CAST(TotalAmount AS REAL) = CAST(TotalAmount AS INTEGER) AND (Kind <> 'Prescription' OR (PrescriptionId IS NOT NULL AND PatientId IS NOT NULL)) AND (Status <> 'Completed' OR (CompletedAt IS NOT NULL AND PaymentMethod IS NOT NULL AND ((Channel='Counter' AND PaymentMethod='Cash') OR (Channel='Online' AND PaymentMethod='ManualQR'))))");
                        });

                    b.HasDiscriminator().HasValue("Prescription");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.BatchAllocation", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.DrugBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.SaleItem", null)
                        .WithMany("Allocations")
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.CartItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.DrugBatch", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany("Batches")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Invoice", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Sale", "Sale")
                        .WithOne()
                        .HasForeignKey("Pharmacy.Core.Domain.Invoice", "SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Order", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.OrderItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Payment", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithOne()
                        .HasForeignKey("Pharmacy.Core.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Prescription", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PrescriptionItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Prescription", null)
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Sale", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.SaleItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.StockReservation", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.PrescriptionItem", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Drug", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.SaleItem", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
