// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pharmacy.Core.Data;

#nullable disable

namespace Pharmacy.Core.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresPharmacyDbContext))]
    [Migration("20261006161045_OrderReadyAt")]
    partial class OrderReadyAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pharmacy")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pharmacy.Core.Data.DailySequence", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("DailySequence", "pharmacy");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.BatchAllocation", b =>
                {
                    b.Property<string>("AllocationId")
                        .HasColumnType("text");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SaleItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AllocationId");

                    b.HasIndex("BatchId");

                    b.HasIndex("SaleItemId");

                    b.ToTable("BatchAllocations", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_BatchAllocation_AllocationQuantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.CartItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DrugId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DrugId");

                    b.HasIndex("DrugId");

                    b.ToTable("CartItems", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_CartQuantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Drug", b =>
                {
                    b.Property<string>("DrugId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("boolean");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("boolean");

                    b.Property<string>("SaleUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_Drug_DrugRules", "length(trim(\"Name\")) > 0 AND length(trim(\"SaleUnit\")) > 0 AND \"UnitPrice\" > 0 AND \"UnitPrice\" = trunc(\"UnitPrice\") AND \"LowStockThreshold\" >= 0 AND (\"IsControlled\" = FALSE OR \"RequiresPrescription\" = TRUE)");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.DrugBatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("BatchId");

                    b.HasIndex("DrugId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("DrugBatches", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_DrugBatch_BatchQuantity", "\"InitialQuantity\" > 0 AND \"Quantity\" >= 0 AND \"Quantity\" <= \"InitialQuantity\" AND length(trim(\"BatchNumber\")) > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("Invoices", "pharmacy");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandledByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiveMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaleKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("HandledByUserId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_Order_OrderRules", "\"SaleKind\" IN ('OTC','Prescription') AND \"ReceiveMethod\" IN ('Pickup','Delivery') AND \"Status\" IN ('WaitingReview','AwaitingPayment','Preparing','Delivering','Completed','Cancelled','Rejected') AND length(trim(\"ReceiverName\")) > 0 AND length(trim(\"Phone\")) > 0 AND (\"ReceiveMethod\" <> 'Delivery' OR (\"Address\" IS NOT NULL AND length(trim(\"Address\")) > 0)) AND (\"SaleKind\" <> 'Prescription' OR (\"PrescriptionId\" IS NOT NULL AND \"PatientId\" IS NOT NULL)) AND \"TotalAmount\" >= 0 AND \"TotalAmount\" = trunc(\"TotalAmount\")");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasColumnType("text");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("OrderItemId");

                    b.HasIndex("DrugId");

                    b.HasIndex("OrderId", "DrugId")
                        .IsUnique();

                    b.ToTable("OrderItems", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Money", "\"Quantity\" > 0 AND \"UnitPrice\" > 0 AND \"UnitPrice\" = trunc(\"UnitPrice\") AND \"LineTotal\" = \"Quantity\" * \"UnitPrice\"");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ReceivedAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BankReference")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Confirmed'");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_PaymentRules", "\"ExpectedAmount\" > 0 AND \"ExpectedAmount\" = trunc(\"ExpectedAmount\") AND (\"ReceivedAmount\" IS NULL OR (\"ReceivedAmount\" >= 0 AND \"ReceivedAmount\" = trunc(\"ReceivedAmount\"))) AND (\"Status\" <> 'Confirmed' OR (\"ApprovedByUserId\" IS NOT NULL AND \"ApprovedAt\" IS NOT NULL AND \"ReceivedAmount\" >= \"ExpectedAmount\"))");

                            t.HasCheckConstraint("CK_Payment_PaymentStatus", "\"Status\" IN ('PendingReview','Confirmed','Closed') AND length(trim(\"BankName\")) > 0 AND length(trim(\"AccountNumber\")) > 0 AND length(trim(\"AccountName\")) > 0 AND length(trim(\"QrImagePath\")) > 0");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PaymentSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrImagePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentSettings", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSetting_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Prescription", b =>
                {
                    b.Property<string>("PrescriptionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriberName")
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("Prescriptions", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_Prescription_PrescriptionRules", "\"Status\" IN ('PendingReview','Approved','Rejected','Cancelled') AND length(trim(\"PatientId\")) > 0 AND length(trim(\"PatientName\")) > 0 AND (\"IssueDate\" IS NULL OR \"ValidUntil\" IS NULL OR \"IssueDate\" <= \"ValidUntil\") AND (\"Status\" <> 'Approved' OR (\"IssueDate\" IS NOT NULL AND \"ValidUntil\" IS NOT NULL AND \"PrescriberName\" IS NOT NULL AND length(trim(\"PrescriberName\")) > 0))");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PrescriptionItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<int>("DispensedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrescribedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("PrescriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PrescriptionId", "DrugId")
                        .IsUnique();

                    b.ToTable("PrescriptionItems", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_PrescriptionItem_PrescriptionQuantity", "\"PrescribedQuantity\" > 0 AND \"DispensedQuantity\" >= 0 AND \"DispensedQuantity\" <= \"PrescribedQuantity\"");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Sale", b =>
                {
                    b.Property<string>("SaleId")
                        .HasColumnType("text");

                    b.Property<string>("BuyerUserId")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("SaleId");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Completed' AND \"OrderId\" IS NOT NULL");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Sales", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_Sale_SaleRules", "\"Kind\" IN ('OTC','Prescription') AND \"Channel\" IN ('Counter','Online') AND \"Status\" IN ('Draft','Completed','Cancelled') AND \"TotalAmount\" >= 0 AND \"TotalAmount\" = trunc(\"TotalAmount\") AND (\"Kind\" <> 'Prescription' OR (\"PrescriptionId\" IS NOT NULL AND \"PatientId\" IS NOT NULL)) AND (\"Status\" <> 'Completed' OR (\"CompletedAt\" IS NOT NULL AND \"PaymentMethod\" IS NOT NULL AND ((\"Channel\"='Counter' AND \"PaymentMethod\"='Cash') OR (\"Channel\"='Online' AND \"PaymentMethod\"='ManualQR'))))");
                        });

                    b.HasDiscriminator<string>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.SaleItem", b =>
                {
                    b.Property<string>("SaleItemId")
                        .HasColumnType("text");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("SaleItemId");

                    b.HasIndex("DrugId");

                    b.HasIndex("SaleId", "DrugId")
                        .IsUnique();

                    b.ToTable("SaleItems", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_SaleItem_Money", "\"Quantity\" > 0 AND \"UnitPrice\" > 0 AND \"UnitPrice\" = trunc(\"UnitPrice\") AND \"LineTotal\" = \"Quantity\" * \"UnitPrice\"");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.StockReservation", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasColumnType("text");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionItemId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReservationId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PrescriptionItemId");

                    b.HasIndex("OrderId", "DrugId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("StockReservations", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_StockReservation_ReservationRules", "\"Quantity\" > 0 AND \"Status\" IN ('Active','Consumed','Released')");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.UserAccount", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("UserAccounts", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccount_AccountRules", "length(\"Username\") BETWEEN 3 AND 30 AND \"Username\" ~ '^[A-Za-z0-9._-]+$' AND length(\"PasswordHash\") > 0 AND \"NormalizedUsername\" = upper(trim(\"Username\")) AND \"Role\" IN ('User','Staff','Admin')");
                        });
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.OTCSale", b =>
                {
                    b.HasBaseType("Pharmacy.Core.Domain.Sale");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Sale_SaleRules", "\"Kind\" IN ('OTC','Prescription') AND \"Channel\" IN ('Counter','Online') AND \"Status\" IN ('Draft','Completed','Cancelled') AND \"TotalAmount\" >= 0 AND \"TotalAmount\" = trunc(\"TotalAmount\") AND (\"Kind\" <> 'Prescription' OR (\"PrescriptionId\" IS NOT NULL AND \"PatientId\" IS NOT NULL)) AND (\"Status\" <> 'Completed' OR (\"CompletedAt\" IS NOT NULL AND \"PaymentMethod\" IS NOT NULL AND ((\"Channel\"='Counter' AND \"PaymentMethod\"='Cash') OR (\"Channel\"='Online' AND \"PaymentMethod\"='ManualQR'))))");
                        });

                    b.HasDiscriminator().HasValue("OTC");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PrescriptionSale", b =>
                {
                    b.HasBaseType("Pharmacy.Core.Domain.Sale");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Sale_SaleRules", "\"Kind\" IN ('OTC','Prescription') AND \"Channel\" IN ('Counter','Online') AND \"Status\" IN ('Draft','Completed','Cancelled') AND \"TotalAmount\" >= 0 AND \"TotalAmount\" = trunc(\"TotalAmount\") AND (\"Kind\" <> 'Prescription' OR (\"PrescriptionId\" IS NOT NULL AND \"PatientId\" IS NOT NULL)) AND (\"Status\" <> 'Completed' OR (\"CompletedAt\" IS NOT NULL AND \"PaymentMethod\" IS NOT NULL AND ((\"Channel\"='Counter' AND \"PaymentMethod\"='Cash') OR (\"Channel\"='Online' AND \"PaymentMethod\"='ManualQR'))))");
                        });

                    b.HasDiscriminator().HasValue("Prescription");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.BatchAllocation", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.DrugBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.SaleItem", null)
                        .WithMany("Allocations")
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.CartItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.DrugBatch", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany("Batches")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Invoice", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Sale", "Sale")
                        .WithOne()
                        .HasForeignKey("Pharmacy.Core.Domain.Invoice", "SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Order", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.OrderItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Payment", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithOne()
                        .HasForeignKey("Pharmacy.Core.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Prescription", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.PrescriptionItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Prescription", null)
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Sale", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacy.Core.Domain.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.SaleItem", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.StockReservation", b =>
                {
                    b.HasOne("Pharmacy.Core.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Core.Domain.PrescriptionItem", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Drug", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pharmacy.Core.Domain.SaleItem", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
