DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'pharmacy') THEN
        CREATE SCHEMA pharmacy;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS pharmacy."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'pharmacy') THEN
            CREATE SCHEMA pharmacy;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."DailySequence" (
        "Key" text NOT NULL,
        "Value" integer NOT NULL,
        CONSTRAINT "PK_DailySequence" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."Drugs" (
        "DrugId" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "ImagePath" text,
        "SaleUnit" text NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "LowStockThreshold" integer NOT NULL,
        "RequiresPrescription" boolean NOT NULL,
        "IsControlled" boolean NOT NULL,
        "IsForSale" boolean NOT NULL,
        CONSTRAINT "PK_Drugs" PRIMARY KEY ("DrugId"),
        CONSTRAINT "CK_Drug_DrugRules" CHECK (length(trim("Name")) > 0 AND length(trim("SaleUnit")) > 0 AND "UnitPrice" > 0 AND "UnitPrice" = trunc("UnitPrice") AND "LowStockThreshold" >= 0 AND ("IsControlled" = FALSE OR "RequiresPrescription" = TRUE))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."PaymentSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BankName" text NOT NULL,
        "AccountNumber" text NOT NULL,
        "AccountName" text NOT NULL,
        "QrImagePath" text,
        CONSTRAINT "PK_PaymentSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_PaymentSetting_Singleton" CHECK ("Id" = 1)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."UserAccounts" (
        "UserId" text NOT NULL,
        "Username" text NOT NULL,
        "NormalizedUsername" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        CONSTRAINT "PK_UserAccounts" PRIMARY KEY ("UserId"),
        CONSTRAINT "CK_UserAccount_AccountRules" CHECK (length("Username") BETWEEN 3 AND 30 AND "Username" ~ '^[A-Za-z0-9._-]+$' AND length("PasswordHash") > 0 AND "NormalizedUsername" = upper(trim("Username")) AND "Role" IN ('User','Staff','Admin'))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."DrugBatches" (
        "BatchId" text NOT NULL,
        "DrugId" text NOT NULL,
        "BatchNumber" text NOT NULL,
        "ExpiryDate" date NOT NULL,
        "InitialQuantity" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "Version" integer NOT NULL,
        CONSTRAINT "PK_DrugBatches" PRIMARY KEY ("BatchId"),
        CONSTRAINT "CK_DrugBatch_BatchQuantity" CHECK ("InitialQuantity" > 0 AND "Quantity" >= 0 AND "Quantity" <= "InitialQuantity" AND length(trim("BatchNumber")) > 0),
        CONSTRAINT "FK_DrugBatches_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES pharmacy."Drugs" ("DrugId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."CartItems" (
        "UserId" text NOT NULL,
        "DrugId" text NOT NULL,
        "Quantity" integer NOT NULL,
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("UserId", "DrugId"),
        CONSTRAINT "CK_CartItem_CartQuantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_CartItems_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES pharmacy."Drugs" ("DrugId") ON DELETE RESTRICT,
        CONSTRAINT "FK_CartItems_UserAccounts_UserId" FOREIGN KEY ("UserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."Prescriptions" (
        "PrescriptionId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "OwnerUserId" text,
        "CreatedByUserId" text NOT NULL,
        "PatientId" text NOT NULL,
        "PatientName" text NOT NULL,
        "PrescriberName" text,
        "ImagePath" text,
        "IssueDate" date,
        "ValidUntil" date,
        "Status" text NOT NULL,
        "ReviewedByUserId" text,
        "ReviewedAt" timestamp with time zone,
        "ReviewNote" text,
        CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("PrescriptionId"),
        CONSTRAINT "CK_Prescription_PrescriptionRules" CHECK ("Status" IN ('PendingReview','Approved','Rejected','Cancelled') AND length(trim("PatientId")) > 0 AND length(trim("PatientName")) > 0 AND ("IssueDate" IS NULL OR "ValidUntil" IS NULL OR "IssueDate" <= "ValidUntil") AND ("Status" <> 'Approved' OR ("IssueDate" IS NOT NULL AND "ValidUntil" IS NOT NULL AND "PrescriberName" IS NOT NULL AND length(trim("PrescriberName")) > 0))),
        CONSTRAINT "FK_Prescriptions_UserAccounts_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Prescriptions_UserAccounts_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Prescriptions_UserAccounts_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."Orders" (
        "OrderId" text NOT NULL,
        "UserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "SaleKind" text NOT NULL,
        "ReceiverName" text NOT NULL,
        "Phone" text NOT NULL,
        "ReceiveMethod" text NOT NULL,
        "Address" text,
        "PrescriptionId" text,
        "PatientId" text,
        "HandledByUserId" text,
        "Status" text NOT NULL,
        "TotalAmount" numeric NOT NULL,
        "Note" text,
        "Version" integer NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
        CONSTRAINT "CK_Order_OrderRules" CHECK ("SaleKind" IN ('OTC','Prescription') AND "ReceiveMethod" IN ('Pickup','Delivery') AND "Status" IN ('WaitingReview','AwaitingPayment','Preparing','Delivering','Completed','Cancelled','Rejected') AND length(trim("ReceiverName")) > 0 AND length(trim("Phone")) > 0 AND ("ReceiveMethod" <> 'Delivery' OR ("Address" IS NOT NULL AND length(trim("Address")) > 0)) AND ("SaleKind" <> 'Prescription' OR ("PrescriptionId" IS NOT NULL AND "PatientId" IS NOT NULL)) AND "TotalAmount" >= 0 AND "TotalAmount" = trunc("TotalAmount")),
        CONSTRAINT "FK_Orders_Prescriptions_PrescriptionId" FOREIGN KEY ("PrescriptionId") REFERENCES pharmacy."Prescriptions" ("PrescriptionId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_UserAccounts_HandledByUserId" FOREIGN KEY ("HandledByUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_UserAccounts_UserId" FOREIGN KEY ("UserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."PrescriptionItems" (
        "ItemId" text NOT NULL,
        "PrescriptionId" text NOT NULL,
        "DrugId" text NOT NULL,
        "PrescribedQuantity" integer NOT NULL,
        "DispensedQuantity" integer NOT NULL,
        "Version" integer NOT NULL,
        CONSTRAINT "PK_PrescriptionItems" PRIMARY KEY ("ItemId"),
        CONSTRAINT "CK_PrescriptionItem_PrescriptionQuantity" CHECK ("PrescribedQuantity" > 0 AND "DispensedQuantity" >= 0 AND "DispensedQuantity" <= "PrescribedQuantity"),
        CONSTRAINT "FK_PrescriptionItems_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES pharmacy."Drugs" ("DrugId") ON DELETE RESTRICT,
        CONSTRAINT "FK_PrescriptionItems_Prescriptions_PrescriptionId" FOREIGN KEY ("PrescriptionId") REFERENCES pharmacy."Prescriptions" ("PrescriptionId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."OrderItems" (
        "OrderItemId" text NOT NULL,
        "OrderId" text NOT NULL,
        "DrugId" text NOT NULL,
        "DrugName" text NOT NULL,
        "Unit" text NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "LineTotal" numeric NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("OrderItemId"),
        CONSTRAINT "CK_OrderItem_Money" CHECK ("Quantity" > 0 AND "UnitPrice" > 0 AND "UnitPrice" = trunc("UnitPrice") AND "LineTotal" = "Quantity" * "UnitPrice"),
        CONSTRAINT "FK_OrderItems_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES pharmacy."Drugs" ("DrugId") ON DELETE RESTRICT,
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES pharmacy."Orders" ("OrderId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."Payments" (
        "PaymentId" text NOT NULL,
        "OrderId" text NOT NULL,
        "Status" text NOT NULL,
        "ExpectedAmount" numeric NOT NULL,
        "ReceivedAmount" numeric,
        "BankReference" text,
        "BankName" text NOT NULL,
        "AccountNumber" text NOT NULL,
        "AccountName" text NOT NULL,
        "QrImagePath" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ReceivedAt" timestamp with time zone,
        "ApprovedByUserId" text,
        "ApprovedAt" timestamp with time zone,
        "ReviewNote" text,
        "Version" integer NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId"),
        CONSTRAINT "CK_Payment_PaymentRules" CHECK ("ExpectedAmount" > 0 AND "ExpectedAmount" = trunc("ExpectedAmount") AND ("ReceivedAmount" IS NULL OR ("ReceivedAmount" >= 0 AND "ReceivedAmount" = trunc("ReceivedAmount"))) AND ("Status" <> 'Confirmed' OR ("BankReference" IS NOT NULL AND "ApprovedByUserId" IS NOT NULL AND "ApprovedAt" IS NOT NULL AND "ReceivedAmount" >= "ExpectedAmount"))),
        CONSTRAINT "CK_Payment_PaymentStatus" CHECK ("Status" IN ('PendingReview','Confirmed','Closed') AND length(trim("BankName")) > 0 AND length(trim("AccountNumber")) > 0 AND length(trim("AccountName")) > 0 AND length(trim("QrImagePath")) > 0),
        CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES pharmacy."Orders" ("OrderId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Payments_UserAccounts_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."Sales" (
        "SaleId" text NOT NULL,
        "Channel" text NOT NULL,
        "Kind" text NOT NULL,
        "Status" text NOT NULL,
        "CreatedByUserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "BuyerUserId" text,
        "OrderId" text,
        "PrescriptionId" text,
        "PatientId" text,
        "CompletedAt" timestamp with time zone,
        "TotalAmount" numeric NOT NULL,
        "PaymentMethod" text,
        "Version" integer NOT NULL,
        CONSTRAINT "PK_Sales" PRIMARY KEY ("SaleId"),
        CONSTRAINT "CK_Sale_SaleRules" CHECK ("Kind" IN ('OTC','Prescription') AND "Channel" IN ('Counter','Online') AND "Status" IN ('Draft','Completed','Cancelled') AND "TotalAmount" >= 0 AND "TotalAmount" = trunc("TotalAmount") AND ("Kind" <> 'Prescription' OR ("PrescriptionId" IS NOT NULL AND "PatientId" IS NOT NULL)) AND ("Status" <> 'Completed' OR ("CompletedAt" IS NOT NULL AND "PaymentMethod" IS NOT NULL AND (("Channel"='Counter' AND "PaymentMethod"='Cash') OR ("Channel"='Online' AND "PaymentMethod"='ManualQR'))))),
        CONSTRAINT "FK_Sales_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES pharmacy."Orders" ("OrderId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sales_Prescriptions_PrescriptionId" FOREIGN KEY ("PrescriptionId") REFERENCES pharmacy."Prescriptions" ("PrescriptionId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sales_UserAccounts_BuyerUserId" FOREIGN KEY ("BuyerUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sales_UserAccounts_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES pharmacy."UserAccounts" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."StockReservations" (
        "ReservationId" text NOT NULL,
        "OrderId" text NOT NULL,
        "DrugId" text NOT NULL,
        "PrescriptionItemId" text,
        "Quantity" integer NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_StockReservations" PRIMARY KEY ("ReservationId"),
        CONSTRAINT "CK_StockReservation_ReservationRules" CHECK ("Quantity" > 0 AND "Status" IN ('Active','Consumed','Released')),
        CONSTRAINT "FK_StockReservations_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES pharmacy."Drugs" ("DrugId") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockReservations_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES pharmacy."Orders" ("OrderId") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockReservations_PrescriptionItems_PrescriptionItemId" FOREIGN KEY ("PrescriptionItemId") REFERENCES pharmacy."PrescriptionItems" ("ItemId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."Invoices" (
        "InvoiceId" text NOT NULL,
        "SaleId" text NOT NULL,
        "IssuedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Invoices" PRIMARY KEY ("InvoiceId"),
        CONSTRAINT "FK_Invoices_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES pharmacy."Sales" ("SaleId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."SaleItems" (
        "SaleItemId" text NOT NULL,
        "SaleId" text NOT NULL,
        "DrugId" text NOT NULL,
        "DrugName" text NOT NULL,
        "Unit" text NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "LineTotal" numeric NOT NULL,
        "IsSealed" boolean NOT NULL,
        CONSTRAINT "PK_SaleItems" PRIMARY KEY ("SaleItemId"),
        CONSTRAINT "CK_SaleItem_Money" CHECK ("Quantity" > 0 AND "UnitPrice" > 0 AND "UnitPrice" = trunc("UnitPrice") AND "LineTotal" = "Quantity" * "UnitPrice"),
        CONSTRAINT "FK_SaleItems_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES pharmacy."Drugs" ("DrugId") ON DELETE RESTRICT,
        CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES pharmacy."Sales" ("SaleId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE TABLE pharmacy."BatchAllocations" (
        "AllocationId" text NOT NULL,
        "SaleItemId" text NOT NULL,
        "BatchId" text NOT NULL,
        "Quantity" integer NOT NULL,
        CONSTRAINT "PK_BatchAllocations" PRIMARY KEY ("AllocationId"),
        CONSTRAINT "CK_BatchAllocation_AllocationQuantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_BatchAllocations_DrugBatches_BatchId" FOREIGN KEY ("BatchId") REFERENCES pharmacy."DrugBatches" ("BatchId") ON DELETE RESTRICT,
        CONSTRAINT "FK_BatchAllocations_SaleItems_SaleItemId" FOREIGN KEY ("SaleItemId") REFERENCES pharmacy."SaleItems" ("SaleItemId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_BatchAllocations_BatchId" ON pharmacy."BatchAllocations" ("BatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_BatchAllocations_SaleItemId" ON pharmacy."BatchAllocations" ("SaleItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_CartItems_DrugId" ON pharmacy."CartItems" ("DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_DrugBatches_DrugId_BatchNumber" ON pharmacy."DrugBatches" ("DrugId", "BatchNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Invoices_SaleId" ON pharmacy."Invoices" ("SaleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_OrderItems_DrugId" ON pharmacy."OrderItems" ("DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_OrderItems_OrderId_DrugId" ON pharmacy."OrderItems" ("OrderId", "DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Orders_HandledByUserId" ON pharmacy."Orders" ("HandledByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Orders_PrescriptionId" ON pharmacy."Orders" ("PrescriptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Orders_UserId" ON pharmacy."Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Payments_ApprovedByUserId" ON pharmacy."Payments" ("ApprovedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Payments_BankReference" ON pharmacy."Payments" ("BankReference") WHERE "Status" = 'Confirmed';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Payments_OrderId" ON pharmacy."Payments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_PrescriptionItems_DrugId" ON pharmacy."PrescriptionItems" ("DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_PrescriptionItems_PrescriptionId_DrugId" ON pharmacy."PrescriptionItems" ("PrescriptionId", "DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Prescriptions_CreatedByUserId" ON pharmacy."Prescriptions" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Prescriptions_OwnerUserId" ON pharmacy."Prescriptions" ("OwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Prescriptions_ReviewedByUserId" ON pharmacy."Prescriptions" ("ReviewedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_SaleItems_DrugId" ON pharmacy."SaleItems" ("DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_SaleItems_SaleId_DrugId" ON pharmacy."SaleItems" ("SaleId", "DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_BuyerUserId" ON pharmacy."Sales" ("BuyerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_CreatedByUserId" ON pharmacy."Sales" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Sales_OrderId" ON pharmacy."Sales" ("OrderId") WHERE "Status" = 'Completed' AND "OrderId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_PrescriptionId" ON pharmacy."Sales" ("PrescriptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_StockReservations_DrugId" ON pharmacy."StockReservations" ("DrugId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_StockReservations_OrderId_DrugId" ON pharmacy."StockReservations" ("OrderId", "DrugId") WHERE "Status" = 'Active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE INDEX "IX_StockReservations_PrescriptionItemId" ON pharmacy."StockReservations" ("PrescriptionItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_UserAccounts_NormalizedUsername" ON pharmacy."UserAccounts" ("NormalizedUsername");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pharmacy."__EFMigrationsHistory" WHERE "MigrationId" = '20261006041151_InitialPostgres') THEN
    INSERT INTO pharmacy."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261006041151_InitialPostgres', '10.0.11');
    END IF;
END $EF$;
COMMIT;

